kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: chefs-api
  namespace: ec2c6e-tools
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-04-24T17:03:29Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-04-24T17:15:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:output':
            'f:to': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:dockerfile': {}
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy': {}
            'f:type': {}
          'f:triggers': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'chefs-api:v0.0.1'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    dockerfile: dockerfile-api
    git:
      uri: 'https://github.com/bcgov/nr-brmb-chefs.git'
      ref: main
  triggers:
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion:

---

kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: chefs-frontend
  namespace: ec2c6e-tools
  managedFields:
    - manager: Go-http-client
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-04-24T17:03:29Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastVersion': {}
    - manager: Mozilla
      operation: Update
      apiVersion: build.openshift.io/v1
      time: '2023-04-24T17:15:22Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:output':
            'f:to': {}
          'f:runPolicy': {}
          'f:source':
            'f:contextDir': {}
            'f:dockerfile': {}
            'f:git':
              .: {}
              'f:ref': {}
              'f:uri': {}
            'f:type': {}
          'f:strategy':
            'f:dockerStrategy': {}
            'f:type': {}
          'f:triggers': {}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'chefs-frontend:v0.0.1'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    dockerfile: dockerfile-frontend
    git:
      uri: 'https://github.com/bcgov/nr-brmb-chefs.git'
      ref: main
  triggers:
    - type: ConfigChange
  runPolicy: Serial
status:
  lastVersion: