apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\CPreston\CLI Tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: chefs-keycloak
  name: chefs-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chefs-keycloak
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\CPreston\CLI Tools\kompose.exe convert -f docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/chefs-build-common-network: "true"
        io.kompose.service: chefs-keycloak
    spec:
      containers:
        - args:
            - start-dev
            - --http-port=8082
            - -Dkeycloak.migration.action=import
            - -Dkeycloak.migration.provider=singleFile
            - -Dkeycloak.migration.file=/tmp/realm-export.json
            - -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
          env:
            - name: DB_ADDR
              value: postgres
            - name: DB_PASSWORD
              value: admin
            - name: DB_USER
              value: admin
            - name: DB_VENDOR
              value: POSTGRES
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
          image: quay.io/keycloak/keycloak:17.0.1
          name: chefs-keycloak
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
