kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: chefs
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'chefs-api:v0.0.1'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    dockerfile: Dockerfile-chefs
    git:
      uri: 'https://github.com/bcgov/nr-brmb-chefs.git'
      ref: feature/0.0.1
  triggers:
    - type: ConfigChange
  runPolicy: Serial