apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: chefs-npm
  name: chefs-npm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chefs-npm
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chefs-build-common-network: 'true'
        io.kompose.service: chefs-npm
    spec:
      containers:
        - resources: {}
          name: chefs-npm
          env:
            - name: BUCKET_ACCESS_KEY_ID
              value: 
            - name: BUCKET_ID
              value: 
            - name: ENVIRONMENT
              value: 
            - name: REALM
              value:
            - name: CLIENT_SECRET
              value:
            - name: CHEFS_SERVICE_CLIENT
              value:
            - name: CHEFS_SERVICE_PASSWORD
              value:
            - name: DB_USER
              value:
            - name: DB_SECRET
              value:  
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/TOOLS_NAMESPACE/chefs-api@v0.0.1
          args:
            - 
      volumes:
        - name: secret-volume
          secret:
            secretName: realm-export
status: {}
