apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-kc-data
  name: postgres-kc-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-logs
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Mi