kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/chefs-build-common-network: 'true'
        io.kompose.service: postgres
    spec:
      volumes:
        - name: postgres-kc-data
          persistentVolumeClaim:
            claimName: postgres-kc-data
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: postgres
          env:
            - name: POSTGRES_DB
              value: chefs
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: POSTGRES_USER
              value: app
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: postgres-kc-data
              mountPath: /var/lib/postgresql/data
          terminationMessagePolicy: File
          image: 'postgres:14.2'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
